version: '3'
services:
    porg_cms:
        build:
            context: .
        image: porg_cms
        volumes:
          - .:/usr/src/app
        ports:
          - "3000:3000"
        restart: always
        command: bash -c "yarn install --no-bin-links && yarn start"
